apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-sandbox
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    # path to the folder with the YAML manifests
    path: solutions/helm/nginx-deployment
    repoURL: https://github.com/DeaconBlu/udacity
    targetRevision: HEAD
  # Sync policy
  syncPolicy: {}
